### ISSUE TITLE
No way to display `jobs-history -v` output.

### ISSUE THREAD

**Issue by stevenrbrandt** [agaveplatform/agave-togo#14]
Since `jobs-history -v` is the primary way to debug failed jobs, it needs to be available in togo somewhere.

**Comment by deardooley** [comment]
A sample history response for a job is given below. 

```
{
  "status" : "success",
  "message" : null,
  "version" : "2.2.27-rdbda19d",
  "result" : [ 
      {
        "status" : "PENDING",
        "created" : "2019-12-04T15:04:43.000-06:00",
        "createdBy" : "dooley",
        "description" : "Job accepted and queued for submission."
      },
      ...
  ]
}
```
The current fields returned in the event object are: `status`, `created`, `createdBy`, and `description`. The history tab on the job (and app, notification, and system) details view currently dump those values into a table with columns names corresponding to field names. The description column is dumped as is, without auto-linking of urls or markup of any kind. Screenshot is attached below. 

![ToGo Job History Table](https://user-images.githubusercontent.com/785202/78649709-6b08a900-7883-11ea-9614-2afab6c47182.png "ToGo Job History Table")

What can we do to give better visibility to the job execution process? Is the job event history not sufficient for debugging? Would having a button to automatically pull the job stdout and stderr help? How can we improve the process for you?

**Comment by stevenrbrandt** [comment]
OK, good. You can close this one.
